# -*- coding: utf-8 -*-
"""Studentprofile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/160lZVZCk9ZITYk90sXQfFZS-ezEwN0pK
"""

print('subjects' ,', '.join(subjects))

print('name:', student_name)
print('age:', age)
print('subjects:', subjects)

print(student_name, age, subjects)

student_name = 'pavithra'
age= 20
subjects= ['English', 'political', 'eclipse']

print('Student Profile Creator')
