# -*- coding: utf-8 -*-
"""feedback.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hfzBDw_ZHJk7pOpTxdsWTHeG6SNMkilZ
"""

print('Feedback Analyzer')
feedback=input('please enter your Data and data feedback: ')
words= feedback.split()
print('total Word count:', len(words))
print("word count:", len(feedback))
print('word counts:' , feedback.lower().count('data'))
print(words)
print('forward:' ,feedback[:5])
print('reverse:', feedback[-5:])
print('reverse order:',feedback[::-1])
