+# -*- coding: utf-8 -*-
"""retail_inventory_manager.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aYYMNNMV2Kegp4XEmv0TkNGxiR7O5Dte
"""

print(productslist)

print('Retail Inventory Manager')
product_categories=('Electronics', 'Stationary', 'Books')
print(product_categories)
productslist=['fan', 'remote', 'chapter']
new_product=input('please enter a new product: ')
productslist.append(new_product)
index=int(input('enter a name to remove: '))
productslist.pop(index)
print('Final list: ', productslist)
print('Final products: ', product_categories)
