# -*- coding: utf-8 -*-
"""Day40_ListMethods_Slicing.ipnb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfzF6hGAWkvRGqcphrtXnfFfe5uGOTv3
"""

print(' Day 40 – List Methods and Slicing')
print('Contact Directory')
contact_fields = ["contact's name", "phone number", "email address"]
print(contact_fields)
print('1. 2Dlist')
contacts=[["amirtha","9478565421", "amirtha@gmail.com"]]
contacts.append(["prema","9475465421", "prema@gmail.com"])
contacts.append(["sharvani", "9456587895", "sharvani@gmail.com"])
print(contacts)
print('2. Allow the user to add a new contact:')
contact_name_input = input(' enter contact name ')

print('4. Get name from user and add it to the list')
contact_name_input = input('enter contact name:')
phone_number_input = input('enter phone number for new contact: ')
email_address_input = input('enter email address for new contact: ')

new_contact = [contact_name_input, phone_number_input, email_address_input]
contacts.append(new_contact)

print('\nUpdated contacts list:')
print(contacts)

print('3. Remove the last item')
print('\nRemoving the last contact:')
contacts.pop()
print(contacts)

print(' 5. Sort the list in ascending order based on any values')
print('\nSorting contacts :')
contacts.sort()
print(contacts)