# -*- coding: utf-8 -*-
"""Day41_Oper_Condition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u69jSE2BGkTuRGZZ_I9zrr1PzxrwpDaB
"""

print('1. Ask the user to enter their weight (in kilograms) and height (in meters).')
weight=int(input('enter your weight in kgms '  ))
height=int(input('enter your height in meters ' ))

print('2. Calculate their BMI using the formula BMI = weight / (height × height).')
bmi= weight / (height * height)
print(f'your bmi is {bmi}')

print('3. Classify the BMI as underweight, normal, overweight, or obese using conditional statements.')

if bmi < 2:
     category = 'underweight'
elif bmi >= 2 and bmi< 4:
     category ='normal'
elif bmi >= 4 and bmi < 6:
     category = 'overweight'
else:
     category = 'obese'

print(f'your category is {category}')

print('4. Display the result clearly.')
print(f'your bmi is {bmi}')
print(f'your category is {category}')

print('5. Ensure the weight and height entered are integer numbers.')
print('yes weight and height are in integer numbers')