# -*- coding: utf-8 -*-
"""Day41_Dict_Set_frozenset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nnGQurw4OeJ3ezmMIuP-CnIwnqsuDAEt
"""

print('Day 41 – Dictionary, Set, Frozenset')
print('Project Title: Student Grades & Hobbies Tracker')

print('1. Create a dictionary with student names as keys and their grades as values.')
students={'sikender':20, 'splendor': 30, 'patrick': 40, 'federer': 50}
studentsname=students.keys()
print(studentsname)
studentsgrade=students.values()
print(studentsgrade)

print('2. Allow the user to add or update grades for at least 3 students.')
name1 = input('Enter student name 1 to add/update: ')
grade1=int(input(f'Enter grade for {name1}: '))
name2= input('Enter student name 2 to add/update: ')
grade2=int(input(f'Enter grade for {name2}: '))
name3=input('Enter student name 3 to add/update: ')
grade3=int(input(f'Enter grade for {name3}: '))
students[name1]=grade1
students[name2]=grade2
students[name3]=grade3
print('\nUpdated student grades:')
print(students)

print('3. Create a set of hobbies and allow the user to input at least 3 hobbies.')
hobbies={'waliking', 'Jocking', 'thinking', 'sighting'}
hobbies1=input('your hobby :')
hobbies2=input('your hobby :')
hobbies3=input('your hobby :')
hobbies.add(hobbies1)
hobbies.add(hobbies2)
hobbies.add(hobbies3)
print(hobbies)

print('4. Convert the set of hobbies into a frozenset and display it.')
frozen_hobbies=frozenset(hobbies)
print(frozen_hobbies)